[package]
name = "forge-bot"
version = "0.1.0"
authors = ["alexesmet <alexes.met@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enigo = "0.0.14"
scrap = "0.5.0"
image = "0.23.4"
opencv = "0.39.0"
